services:
  n8n:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: n8n-automation
    ports:
      - "5544:5678"
    volumes:
      - /home/azhar/n8n-data/n8n:/home/node/.n8n
      - /home/azhar/n8n-data/downloads:/data
    environment:
      - N8N_BASIC_AUTH_ACTIVE=true
      - N8N_BASIC_AUTH_USER=${N8N_USER}
      - N8N_BASIC_AUTH_PASSWORD=${N8N_PASSWORD}
    restart: unless-stopped

